### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by reujab** [reujab/bronze#1]
* [x] License
* [x] Document all modules and settings
* [x] Individual files for init scripts
* [x] Fix git branch on detached HEAD
* [x] Emoji/no icons setting
* [x] Remove `segment#visible`
* [x] Allow changing segment separator
* [x] Support generic Linux and BSD
* [x] `cmdtime` threshold
* [x] `time` module
* [x] `user` module
* [x] Merge `dir` and `shortdir` into one module
* [x] Add separator for same background colors
* [x] Add images of `os` icons to the wiki
* [x] `packages` module
* [x] Add packages systemd unit
* [x] Update pacman database before checking for packages
* [x] Allow custom segments with shared objects
* [x] Improve error messages
* [x] Don't rely on `$SHELL`
* [x] Document `BRONZE_DIR_LENGTH`
* [x] Document `plugin`
* [x] Document `packages`
* [x] Fix `BRONZE_DIR_LENGTH`
* [x] `env` module
* [x] Merge Home, Icons and Bronze wiki pages
* [x] Allow icon prefixes other than home
* [x] Allow 256/24-bit colors.
* [x] Release v1.0.0
* [x] Improve installation instructions
* [x] `rss` module
